// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzG5Ti7KbQ_7Db4hwuHUDAZW7Rj375jmk',
    appId: '1:295914680879:web:46a7421ef9b686c147ccda',
    messagingSenderId: '295914680879',
    projectId: 'delveria-f5847',
    authDomain: 'delveria-f5847.firebaseapp.com',
    storageBucket: 'delveria-f5847.firebasestorage.app',
    measurementId: 'G-JRD7Y99EDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDRZ2NZYPLWjMtMHY_kZb0l_zgGrq-rIU',
    appId: '1:295914680879:android:0b84103298cef3fd47ccda',
    messagingSenderId: '295914680879',
    projectId: 'delveria-f5847',
    storageBucket: 'delveria-f5847.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_YBPa03WdqlgulbrQ1n2LlakLUNG6iQ',
    appId: '1:295914680879:ios:81825974ca5761c347ccda',
    messagingSenderId: '295914680879',
    projectId: 'delveria-f5847',
    storageBucket: 'delveria-f5847.firebasestorage.app',
    iosBundleId: 'com.delveria.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6_YBPa03WdqlgulbrQ1n2LlakLUNG6iQ',
    appId: '1:295914680879:ios:81825974ca5761c347ccda',
    messagingSenderId: '295914680879',
    projectId: 'delveria-f5847',
    storageBucket: 'delveria-f5847.firebasestorage.app',
    iosBundleId: 'com.delveria.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzG5Ti7KbQ_7Db4hwuHUDAZW7Rj375jmk',
    appId: '1:295914680879:web:533ed8026ce551c447ccda',
    messagingSenderId: '295914680879',
    projectId: 'delveria-f5847',
    authDomain: 'delveria-f5847.firebaseapp.com',
    storageBucket: 'delveria-f5847.firebasestorage.app',
    measurementId: 'G-YR3H9FZEFL',
  );
}
