// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqHsj4Fv-IyFXZmoQIICpQ3W7t165PCCM',
    appId: '1:764283484292:web:32d6494bc41333a3062ad1',
    messagingSenderId: '764283484292',
    projectId: 'delveria-657b0',
    authDomain: 'delveria-657b0.firebaseapp.com',
    storageBucket: 'delveria-657b0.firebasestorage.app',
    measurementId: 'G-3KBKKQYMD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbFowBj4YNU8Kq88bUG82ViRbcZuBwHys',
    appId: '1:764283484292:android:8a72f494861c4df4062ad1',
    messagingSenderId: '764283484292',
    projectId: 'delveria-657b0',
    storageBucket: 'delveria-657b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgkDqwdRqYN1kaj5ok6NJKceMDCY5Kt8',
    appId: '1:764283484292:ios:5aa81622391ba9ac062ad1',
    messagingSenderId: '764283484292',
    projectId: 'delveria-657b0',
    storageBucket: 'delveria-657b0.firebasestorage.app',
    iosBundleId: 'com.delveria.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPgkDqwdRqYN1kaj5ok6NJKceMDCY5Kt8',
    appId: '1:764283484292:ios:02550f513e784f6b062ad1',
    messagingSenderId: '764283484292',
    projectId: 'delveria-657b0',
    storageBucket: 'delveria-657b0.firebasestorage.app',
    iosBundleId: 'com.example.delveria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqHsj4Fv-IyFXZmoQIICpQ3W7t165PCCM',
    appId: '1:764283484292:web:435d04a9a7d397dc062ad1',
    messagingSenderId: '764283484292',
    projectId: 'delveria-657b0',
    authDomain: 'delveria-657b0.firebaseapp.com',
    storageBucket: 'delveria-657b0.firebasestorage.app',
    measurementId: 'G-D4W47BV7FR',
  );

}